ExpandedVolumePanel: Fix SystemUI FC when expands volume panel from Notifications tile
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

Change-Id: I3f5acf5e39e01cd74b7d039bc2189a9009f2abe7

(cherry picked from commit a1ba48636abd49316d57762087daf34a0479ae56)

(cherry picked from commit a1ba48636abd49316d57762087daf34a0479ae56)